from nflpool.viewmodels.viewmodelbase import ViewModelBase


class PlayerPicksViewModel(ViewModelBase):
    def __init__(self):
        self.afc_east_winner_pick = None
        self.afc_east_second = None
        self.afc_east_last = None
        self.afc_north_winner_pick = None
        self.afc_north_second = None
        self.afc_north_last = None
        self.afc_south_winner_pick = None
        self.afc_south_second = None
        self.afc_south_last = None
        self.afc_west_winner_pick = None
        self.afc_west_second = None
        self.afc_west_last = None
        self.nfc_east_winner_pick = None
        self.nfc_east_second = None
        self.nfc_east_last = None
        self.nfc_north_winner_pick = None
        self.nfc_north_second = None
        self.nfc_north_last = None
        self.nfc_south_winner_pick = None
        self.nfc_south_second = None
        self.nfc_south_last = None
        self.nfc_west_winner_pick = None
        self.nfc_west_second = None
        self.nfc_west_last = None
        self.afc_qb_pick = None
        self.nfc_qb_pick = None
        self.afc_rb_pick = None
        self.nfc_rb_pick = None
        self.afc_rec_pick = None
        self.nfc_rec_pick = None
        self.afc_sacks_pick = None
        self.nfc_sacks_pick = None
        self.afc_int_pick = None
        self.nfc_int_pick = None
        self.afc_wildcard1_pick = None
        self.afc_wildcard2_pick = None
        self.nfc_wildcard1_pick = None
        self.nfc_wildcard2_pick = None
        self.afc_pf_pick = None
        self.nfc_pf_pick = None
        self.specialteams_td_pick = None

    def from_dict(self, data_dict):
        self.afc_east_winner_pick = data_dict.get('afc_east_winner_pick')
        self.afc_east_second = data_dict.get('afc_east_second')
        self.afc_east_last = data_dict.get('afc_east_last')
        self.afc_north_winner_pick = data_dict.get('afc_north_winner_pick')
        self.afc_north_second = data_dict.get('afc_north_second')
        self.afc_north_last = data_dict.get('afc_north_last')
        self.afc_south_winner_pick = data_dict.get('afc_south_winner_pick')
        self.afc_south_second = data_dict.get('afc_south_second')
        self.afc_south_last = data_dict.get('afc_south_last')
        self.afc_west_winner_pick = data_dict.get('afc_west_winner_pick')
        self.afc_west_second = data_dict.get('afc_west_second')
        self.afc_west_last = data_dict.get('afc_west_last')
        self.nfc_east_winner_pick = data_dict.get('nfc_east_winner_pick')
        self.nfc_east_second = data_dict.get('nfc_east_second')
        self.nfc_east_last = data_dict.get('nfc_east_last')
        self.nfc_north_winner_pick = data_dict.get('nfc_north_winner_pick')
        self.nfc_north_second = data_dict.get('nfc_north_second')
        self.nfc_north_last = data_dict.get('nfc_north_last')
        self.nfc_south_winner_pick = data_dict.get('nfc_south_winner_pick')
        self.nfc_south_second = data_dict.get('nfc_south_second')
        self.nfc_south_last = data_dict.get('nfc_south_last')
        self.nfc_west_winner_pick = data_dict.get('nfc_west_winner_pick')
        self.nfc_west_second = data_dict.get('nfc_west_second')
        self.nfc_west_last = data_dict.get('nfc_west_last')
        self.afc_qb_pick = data_dict.get('afc_qb_pick')
        self.nfc_qb_pick = data_dict.get('nfc_qb_pick')
        self.afc_rb_pick = data_dict.get('afc_rb_pick')
        self.nfc_rb_pick = data_dict.get('nfc_rb_pick')
        self.afc_rec_pick = data_dict.get('afc_rec_pick')
        self.nfc_rec_pick = data_dict.get('nfc_rec_pick')
        self.afc_sacks_pick = data_dict.get('afc_sacks_pick')
        self.nfc_sacks_pick = data_dict.get('nfc_sacks_pick')
        self.afc_int_pick = data_dict.get('afc_int_pick')
        self.nfc_int_pick = data_dict.get('nfc_int_pick')
        self.afc_wildcard1_pick = data_dict.get('afc_wildcard1_pick')
        self.afc_wildcard2_pick = data_dict.get('afc_wildcard2_pick')
        self.nfc_wildcard1_pick = data_dict.get('nfc_wildcard1_pick')
        self.nfc_wildcard2_pick = data_dict.get('nfc_wildcard2_pick')
        self.afc_pf_pick = data_dict.get('afc_pf_pick')
        self.nfc_pf_pick = data_dict.get('nfc_pf_pick')
        self.specialteams_td_pick = data_dict.get('specialteams_td_pick')


